# Generated by Django 4.2.9 on 2024-07-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtoms', models.TextField()),
                ('appointemt_status', models.CharField(default='Pending', max_length=100, verbose_name=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')])),
                ('appointment_types', models.CharField(max_length=100, verbose_name=[('online', 'online'), ('offline', 'offline')])),
                ('cancel', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.availaletime')),
            ],
        ),
    ]
