# Generated by Django 4.2.9 on 2024-07-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_review'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointemt_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_types',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.availaletime'),
        ),
    ]
