# Generated by Django 4.2.9 on 2024-07-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='avaiiable_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='avaiiable_time',
            field=models.ManyToManyField(to='doctors.availaletime'),
        ),
    ]
