# Generated by Django 4.2.9 on 2024-07-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_avaiiable_time_doctor_avaiiable_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='user',
        ),
    ]
